name: Test

on: [pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout git repository
        uses: actions/checkout@v2

      - name: Run tests
        run: bash -c "make -C read_tests test"
